spring:
     data:
        elasticsearch: #ElasticsearchProperties
            cluster-name: my-application #默认即为elasticsearch
            cluster-nodes: es.mf.com:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode